import type { ComponentConfig } from "./components/types";

import {
  buttonExamples,
  cardExamples,
  inputExamples,
  badgeExamples,
  avatarExamples,
  tabsExamples,
  progressExamples,
  switchExamples,
  sliderExamples,
  tooltipExamples,
  breadcrumbExamples,
  separatorExamples,
  dialogsExamples,
  selectExamples,
  textareaExamples,
  checkboxExamples,
  radioExamples,
  skeletonExamples,
  tableExamples,
  scrollAreaExamples,
  sheetExamples,
  popoverExamples,
  alertDialogExamples,
  weatherExamples,
  calendarExamples,
  clockExamples,
  stocksExamples,
  statsExamples,
  innovativeExamples,
} from "./components";

// Re-export types for backward compatibility
export type { ComponentExample, ComponentConfig } from "./components/types";

// Re-export all examples for backward compatibility
export {
  buttonExamples,
  cardExamples,
  inputExamples,
  badgeExamples,
  avatarExamples,
  tabsExamples,
  progressExamples,
  switchExamples,
  sliderExamples,
  tooltipExamples,
  breadcrumbExamples,
  separatorExamples,
  dialogsExamples,
  selectExamples,
  textareaExamples,
  checkboxExamples,
  radioExamples,
  skeletonExamples,
  tableExamples,
  scrollAreaExamples,
  sheetExamples,
  popoverExamples,
  alertDialogExamples,
  weatherExamples,
  calendarExamples,
  clockExamples,
  stocksExamples,
  statsExamples,
  innovativeExamples,
} from "./components";

// ========== COMPONENT REGISTRY ==========
export const componentRegistry: Record<string, ComponentConfig> = {
  "glass-alert-dialog": {
    slug: "glass-alert-dialog",
    title: "Alert Dialog",
    description: "Modal dialog component for important confirmations and alerts.",
    registryName: "glass-alert-dialog",
    category: "overlays",
    examples: alertDialogExamples,
  },
  "glass-avatar": {
    slug: "glass-avatar",
    title: "Avatar",
    description: "User avatar component with image and fallback support.",
    registryName: "glass-avatar",
    category: "components",
    examples: avatarExamples,
  },
  "glass-badge": {
    slug: "glass-badge",
    title: "Badge",
    description: "Small label component for status, tags, and categorization.",
    registryName: "glass-badge",
    category: "components",
    examples: badgeExamples,
  },
  "glass-breadcrumb": {
    slug: "glass-breadcrumb",
    title: "Breadcrumb",
    description: "Navigation breadcrumb component showing the current page location.",
    registryName: "glass-breadcrumb",
    category: "components",
    examples: breadcrumbExamples,
  },
  "glass-button": {
    slug: "glass-button",
    title: "Button",
    description:
      "Interactive button components with multiple variants, sizes, and optional glow effects.",
    registryName: "glass-button",
    category: "components",
    examples: buttonExamples,
  },
  "glass-card": {
    slug: "glass-card",
    title: "Card",
    description: "Container components for grouping related content with glass morphism styling.",
    registryName: "glass-card",
    category: "components",
    examples: cardExamples,
  },
  "glass-dialog": {
    slug: "glass-dialog",
    title: "Dialogs",
    description: "Modal dialog components for focused user interactions and forms.",
    registryName: "glass-dialog",
    category: "components",
    examples: dialogsExamples,
  },
  "glass-input": {
    slug: "glass-input",
    title: "Input",
    description: "Text input fields with glass morphism styling for forms and user input.",
    registryName: "glass-input",
    category: "components",
    examples: inputExamples,
  },
  "glass-select": {
    slug: "glass-select",
    title: "Select",
    description: "A dropdown select component with glass morphism styling and smooth animations.",
    registryName: "glass-select",
    category: "forms",
    examples: selectExamples,
  },
  "glass-textarea": {
    slug: "glass-textarea",
    title: "Textarea",
    description: "Multi-line text input with glass morphism styling for longer form content.",
    registryName: "glass-textarea",
    category: "forms",
    examples: textareaExamples,
  },
  "glass-checkbox": {
    slug: "glass-checkbox",
    title: "Checkbox",
    description: "Checkbox input component with glass morphism styling for boolean selections.",
    registryName: "glass-checkbox",
    category: "forms",
    examples: checkboxExamples,
  },
  "glass-radio": {
    slug: "glass-radio",
    title: "Radio",
    description: "Radio button group component for single-choice selections.",
    registryName: "glass-radio",
    category: "forms",
    examples: radioExamples,
  },
  "glass-skeleton": {
    slug: "glass-skeleton",
    title: "Skeleton",
    description: "Placeholder loading components for content that is being fetched.",
    registryName: "glass-skeleton",
    category: "data-display",
    examples: skeletonExamples,
  },
  "glass-table": {
    slug: "glass-table",
    title: "Table",
    description: "Data table component with glass morphism styling for displaying structured data.",
    registryName: "glass-table",
    category: "data-display",
    examples: tableExamples,
  },
  "glass-sheet": {
    slug: "glass-sheet",
    title: "Sheet",
    description: "Slide-out panel component for secondary content and actions.",
    registryName: "glass-sheet",
    category: "overlays",
    examples: sheetExamples,
  },
  "glass-popover": {
    slug: "glass-popover",
    title: "Popover",
    description: "Floating panel component for contextual content and forms.",
    registryName: "glass-popover",
    category: "overlays",
    examples: popoverExamples,
  },

  "glass-separator": {
    slug: "glass-separator",
    title: "Separator",
    description: "Visual divider component for separating content sections.",
    registryName: "glass-separator",
    category: "data-display",
    examples: separatorExamples,
  },
  "glass-scroll-area": {
    slug: "glass-scroll-area",
    title: "Scroll Area",
    description: "Custom scrollable container with glass morphism styled scrollbars.",
    registryName: "glass-scroll-area",
    category: "data-display",
    examples: scrollAreaExamples,
  },

  "glass-tabs": {
    slug: "glass-tabs",
    title: "Tabs",
    description: "Tabbed interface component for organizing content into sections.",
    registryName: "glass-tabs",
    category: "components",
    examples: tabsExamples,
  },

  "glass-progress": {
    slug: "glass-progress",
    title: "Progress",
    description: "Progress indicator component for displaying completion status.",
    registryName: "glass-progress",
    category: "components",
    examples: progressExamples,
  },
  "glass-switch": {
    slug: "glass-switch",
    title: "Switch",
    description: "Toggle switch component for boolean settings.",
    registryName: "glass-switch",
    category: "components",
    examples: switchExamples,
  },
  "glass-slider": {
    slug: "glass-slider",
    title: "Slider",
    description: "Range slider component for selecting values within a range.",
    registryName: "glass-slider",
    category: "components",
    examples: sliderExamples,
  },
  "glass-tooltip": {
    slug: "glass-tooltip",
    title: "Tooltip",
    description: "Tooltip component for displaying additional information on hover.",
    registryName: "glass-tooltip",
    category: "components",
    examples: tooltipExamples,
  },
  "weather-widget": {
    slug: "weather-widget",
    title: "Weather Widgets",
    description: "Weather forecast and conditions display widgets.",
    registryName: "weather-widget",
    category: "widgets",
    examples: weatherExamples,
  },
  "calendar-widget": {
    slug: "calendar-widget",
    title: "Calendar Widgets",
    description: "Calendar and event display widgets.",
    registryName: "calendar-widget",
    category: "widgets",
    examples: calendarExamples,
  },
  "clock-widget": {
    slug: "clock-widget",
    title: "Clock Widgets",
    description: "Time display, timers, and stopwatch widgets.",
    registryName: "clock-widget",
    category: "widgets",
    examples: clockExamples,
  },
  "stock-widget": {
    slug: "stock-widget",
    title: "Stocks Widgets",
    description: "Stock prices, portfolios, and market data.",
    registryName: "stock-widget",
    category: "widgets",
    examples: stocksExamples,
  },
  "stats-widget": {
    slug: "stats-widget",
    title: "Stats Widgets",
    description: "Stats and metrics display widgets.",
    registryName: "stats-widget",
    category: "widgets",
    examples: statsExamples,
  },
  "glass-command-palette": {
    slug: "glass-command-palette",
    title: "Command Palette",
    description: "Command palette component for searching and executing actions.",
    registryName: "glass-command-palette",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-morph-card": {
    slug: "glass-morph-card",
    title: "Morph Card",
    description: "Morph card component for displaying content in a visually appealing way.",
    registryName: "glass-morph-card",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-dock": {
    slug: "glass-dock",
    title: "Dock",
    description: "Dock component for displaying content in a visually appealing way.",
    registryName: "glass-dock",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-gauge": {
    slug: "glass-gauge",
    title: "Gauge",
    description: "Gauge component for displaying progress or performance metrics.",
    registryName: "glass-gauge",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-notification": {
    slug: "glass-notification",
    title: "Notification",
    description: "Notification component for displaying messages and alerts.",
    registryName: "glass-notification",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-ripple": {
    slug: "glass-ripple",
    title: "Ripple",
    description: "Ripple effect component for displaying a ripple effect on an element.",
    registryName: "glass-ripple",
    category: "innovative",
    examples: innovativeExamples,
  },
  "glass-timeline": {
    slug: "glass-timeline",
    title: "Timeline",
    description: "Timeline component for displaying a timeline of events.",
    registryName: "glass-timeline",
    category: "innovative",
    examples: innovativeExamples,
  },
};

// Get all component slugs for generateStaticParams
export function getAllComponentSlugs(): string[] {
  return Object.keys(componentRegistry);
}

// Get component config by slug
export function getComponentBySlug(slug: string): ComponentConfig | undefined {
  return componentRegistry[slug];
}
